services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: unless-stopped

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: galkaev
    ports:
      - 8888:8080
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql: